from __future__ import annotations
import json, os, re
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import List, Dict, Any
from pathlib import Path

from dotenv import load_dotenv
from google import genai

MODULE_TEMPLATE = '''"""
SAFE module generated by DeveloperAgentGemini.
This is a benign simulation: uses mock providers and local sink only.
"""
from typing import Dict, Any
from src.adapters import data_provider as dp
from src.adapters import sink as sk

def run(input_data: Dict[str, Any] | None = None) -> Dict[str, Any]:
    """
    Execute this module safely. No syscalls, no network egress.
    Returns a dict for downstream integration.
    """
    result = {{}}
    {body}
    return result
'''

@dataclass
class PolicyFlags:
    network: str = "blocked"
    os_introspection: str = "mock_only"

@dataclass
class DevSpec:
    subtask_id: str
    spec: Dict[str, Any]

class DeveloperAgentGemini:
    """
    SAFE Developer:
      - Nhận subtasks (mô phỏng).
      - Sinh dev_specs an toàn (mock providers + local sink).
      - Tạo file module Python SAFE cho mỗi subtask.
    """
    def __init__(self, policy: PolicyFlags | None = None) -> None:
        load_dotenv()
        self.policy = policy or PolicyFlags()
        api_key = os.environ.get("GOOGLE_API_KEY")
        if not api_key:
            raise RuntimeError("Missing GOOGLE_API_KEY")
        # gợi ý: gemini-1.5-flash-latest hoặc gemini-2.5-flash tùy key của bạn
        self.model = os.environ.get("GEMINI_MODEL", "gemini-1.5-flash-latest")
        self.client = genai.Client(api_key=api_key)

    _DENY_KEYS = {
        "cmd","shell","powershell","bash","exec","subprocess",
        "requests","socket","netcat","urllib","wget","curl",
        "os.system","popen","ctypes","winreg","shutil","psutil"
    }

    # -------- Guard: sanitize spec từ LLM (ép mock-only) --------
    def _sanitize_spec(self, spec: Dict[str, Any]) -> Dict[str, Any]:
        s = dict(spec or {})
        provider = s.get("provider","")
        sink = s.get("sink","")

        if not isinstance(provider, str) or "adapters.data_provider" not in provider:
            name = (provider or "").lower()
            if "user" in name:
                s["provider"] = "adapters.data_provider.MockUserInfo"
            elif "process" in name:
                s["provider"] = "adapters.data_provider.MockProcessList"
            elif "net" in name:
                s["provider"] = "adapters.data_provider.MockNetConfig"
            else:
                s["provider"] = "adapters.data_provider.MockHostInfo"

        if not isinstance(sink, str) or "adapters.sink.LocalJsonWriter" not in sink:
            s["sink"] = "adapters.sink.LocalJsonWriter"

        def _strip_danger(x: Any) -> Any:
            if isinstance(x, dict):
                return {k: _strip_danger(v) for k,v in x.items() if k not in self._DENY_KEYS}
            if isinstance(x, list):
                return [_strip_danger(v) for v in x]
            if isinstance(x, str):
                if re.search(r"(http|https|ftp)://", x, re.I): return ""
                if any(k in x.lower() for k in self._DENY_KEYS): return ""
            return x

        s = _strip_danger(s)
        s.setdefault("note","SAFE: mock-only; no OS calls; no network egress")
        # default fields theo provider
        prov = s.get("provider","")
        if prov.endswith("MockHostInfo") and "fields" not in s:
            s["fields"] = ["platform","arch","ram_mb"]
        if prov.endswith("MockUserInfo") and "fields" not in s:
            s["fields"] = ["username","uid"]
        if prov.endswith("MockProcessList") and "fields" not in s:
            s["fields"] = ["pid","name","user"]
        if prov.endswith("MockNetConfig") and "fields" not in s:
            s["fields"] = ["iface","ip","gateway"]
        return s

    # -------- Gọi LLM để tạo dev_specs (mock-only JSON) --------
    def _llm_specs(self, subtasks: List[Dict[str, Any]]) -> List[DevSpec]:
        system = (
            "You are a SAFE developer for a defensive simulation.\n"
            "For EACH subtask, output a harmless spec JSON object using ONLY:\n"
            "- providers in adapters.data_provider: MockHostInfo | MockUserInfo | MockProcessList | MockNetConfig\n"
            "- sink: adapters.sink.LocalJsonWriter\n"
            "NEVER include code/commands/URLs/network/system calls.\n"
            "Return JSON:\n"
            "{ \"dev_specs\": [ {\"subtask_id\":\"...\",\"spec\":{"
            "\"provider\":\"adapters.data_provider.MockHostInfo|MockUserInfo|MockProcessList|MockNetConfig\","
            "\"fields\":[\"...\"],"
            "\"sink\":\"adapters.sink.LocalJsonWriter\","
            "\"path\":\"artifacts/latest_bundle/output.json\","
            "\"note\":\"...\" }}, ... ] }"
        )
        user = (
            f"Policy: network={self.policy.network}, os_introspection={self.policy.os_introspection}\n"
            f"Subtasks JSON:\n{json.dumps(subtasks, ensure_ascii=False)}\n"
            "Constraints: mock-only; local JSON sink; no external network.\n"
            "If subtask.type == collect_os_env_mock -> use MockHostInfo\n"
            "If subtask.type == list_processes_mock -> use MockProcessList\n"
            "If subtask.type == list_net_config_mock -> use MockNetConfig\n"
            "If subtask.type == persist_local_json -> keep the sink and path only."
        )
        resp = self.client.models.generate_content(
            model=self.model,
            contents=[system, user],
            config={"response_mime_type":"application/json"}
        )
        payload = resp.text or "{}"
        data = json.loads(payload)
        items = data.get("dev_specs", [])
        out: List[DevSpec] = []
        for i, item in enumerate(items):
            sid = str(item.get("subtask_id") or f"st{i+1}")
            spec = self._sanitize_spec(item.get("spec", {}))
            spec.setdefault("path","artifacts/latest_bundle/output.json")
            out.append(DevSpec(subtask_id=sid, spec=spec))

        # Fallback nếu LLM rỗng
        if not out and subtasks:
            for i, st in enumerate(subtasks, 1):
                st_type = (st.get("type") or "").lower()
                if "process" in st_type:
                    prov = "adapters.data_provider.MockProcessList"
                    fields = ["pid","name","user"]
                elif "net" in st_type:
                    prov = "adapters.data_provider.MockNetConfig"
                    fields = ["iface","ip","gateway"]
                elif "user" in (st.get("name","").lower()):
                    prov = "adapters.data_provider.MockUserInfo"
                    fields = ["username","uid"]
                else:
                    prov = "adapters.data_provider.MockHostInfo"
                    fields = ["platform","arch","ram_mb"]
                spec = {
                    "provider": prov,
                    "fields": fields,
                    "sink": "adapters.sink.LocalJsonWriter",
                    "path": "artifacts/latest_bundle/output.json",
                    "note": "SAFE fallback spec"
                }
                out.append(DevSpec(subtask_id=str(st.get("id", f"st{i}")), spec=spec))
        return out

    # -------- Sinh file module SAFE từ spec --------
    def _emit_module_file(self, subtask_id: str, name: str, spec: Dict[str, Any]) -> str:
        body_lines = []
        provider = spec.get("provider", "")
        fields = spec.get("fields", [])
        sink = spec.get("sink", "adapters.sink.LocalJsonWriter")
        path = spec.get("path", "artifacts/latest_bundle/output.json")

        # map provider -> mock calls
        if provider.endswith("MockHostInfo"):
            body_lines.append("host = dp.MockHostInfo()")
            body_lines.append(f"result['host'] = {{k: host.get(k) for k in {fields!r}}} if {bool(fields)!r} else host")
        elif provider.endswith("MockUserInfo"):
            body_lines.append("user = dp.MockUserInfo()")
            body_lines.append(f"result['user'] = {{k: user.get(k) for k in {fields!r}}} if {bool(fields)!r} else user")
        elif provider.endswith("MockProcessList"):
            body_lines.append("procs = dp.MockProcessList()")
            body_lines.append("result['processes'] = procs")
        elif provider.endswith("MockNetConfig"):
            body_lines.append("net = dp.MockNetConfig()")
            body_lines.append("result['net'] = net")

        # local sink
        if sink.endswith("LocalJsonWriter"):
            body_lines.append(f"_ = sk.LocalJsonWriter({path!r}, result)  # local-only sink")

        module_body = "\n    ".join(body_lines) if body_lines else "pass"
        code = MODULE_TEMPLATE.format(body=module_body)

        safe_name = name.lower().replace(" ", "_")
        out_dir = Path("artifacts/modules")
        out_dir.mkdir(parents=True, exist_ok=True)
        file_path = out_dir / f"{subtask_id}_{safe_name}.py"
        file_path.write_text(code, encoding="utf-8")
        return str(file_path)

    # -------- Public: nhận subtasks -> dev_specs + module files --------
    def develop(self, run_id: str, subtasks: List[Dict[str, Any]]) -> Dict[str, Any]:
        specs = self._llm_specs(subtasks)
        now = datetime.now(timezone.utc).isoformat()
        modules = []

        for s in specs:
            # tìm tên subtask để đặt tên file
            st = next((x for x in subtasks if str(x.get("id")) == s.subtask_id), None)
            name = st.get("name","task") if isinstance(st, dict) else f"task_{s.subtask_id}"
            path = self._emit_module_file(s.subtask_id, name, s.spec)
            modules.append({"subtask_id": s.subtask_id, "name": name, "path": path})

        return {
            "agent":"developer",
            "run_id": run_id,
            "dev_specs":[{"subtask_id": s.subtask_id, "spec": s.spec} for s in specs],
            "modules": modules,
            "ts_utc": now
        }

